wunderground/urls.py
"""
project urls here.
"""
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^blog/', include('blog.urls')),
    # url(r'^admin/', include(admin.site.urls)),

    url(r'^$', 'wunderground.views.home', name='home'),
    url(r'^city/add/$', 'wunderground.views.add_station', name='add-city'),
    url(r'^plot-graph/$', 'wunderground.views.plot_graph', name='plot-graph'),
)

wunderground/models.py
"""
Models related to project.
"""
from django.db import models


class Station(models.Model):
    zip_num = models.CharField(max_length=10, unique=True)
    state = models.CharField(max_length=100)
    city = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('state', 'city')
        unique_together = (("state", "city"),)
        db_table = 'station'
        verbose_name_plural = 'stations'

    def get_zip(self):
        return self.zip_num

wunderground/forms.py
"""
Project forms module.
"""
from django import forms
from django.forms import ModelForm
from django.conf import settings
from django.utils.translation import ugettext_lazy as _
from wunderground.models import Station

WP_CHOICES = settings.W_PARAMETERS


class StationForm(ModelForm):
    class Meta:
        model = Station


class CheckWeatherForm(forms.Form):
    state = forms.ChoiceField(required=True, choices=[])
    city = forms.ChoiceField(required=True, choices=[])
    wp = forms.ChoiceField(required=True, choices=WP_CHOICES)
    start_date = forms.DateField(required=True)
    end_date = forms.DateField(required=True)

    def __init__(self, *args, **kwargs):
        super(CheckWeatherForm, self).__init__(*args, **kwargs)
        stations = Station.objects.all()
        STATE_CHOICES = [(st.state, st.state) for st in stations]
        CITY_CHOICES = [(st.city, st.city) for st in stations]
        self.fields['state'] = forms.ChoiceField(choices=STATE_CHOICES)
        self.fields['city'] = forms.ChoiceField(choices=CITY_CHOICES)

    def clean(self):
        if 'start_date' in self.cleaned_data and 'end_date' in self.cleaned_data:
            if self.cleaned_data['start_date'] >= self.cleaned_data['end_date']:
                raise forms.ValidationError(_("Start Date can not be greater then or equal to End Date."))
        return self.cleaned_data

wunderground/views.py
"""
all business logic here.
"""
from datetime import date
from django.template import RequestContext
from django.shortcuts import render_to_response

from wunderground.models import Station
from wunderground.forms import StationForm, CheckWeatherForm
from wunderground.utils import get_data


def home(request):
    """
    """
    form = CheckWeatherForm()
    if request.method == 'GET':
        return render_to_response("home.html", {'form': form},
            context_instance=RequestContext(request))

    elif request.method == 'POST':
        form = CheckWeatherForm(request.POST)
        if form.is_valid():
            try:
                # get date from POST request
                city = form.data['city']
                state = form.data['state']
                wp = form.data['wp'] # weather parameter
                station = Station.objects.get(city=city, state=state)
                zip_num = station.zip_num
                start_date = form.cleaned_data['start_date'] # start date
                end_date = form.cleaned_data['end_date'] # end date

                # get data from wunderground API's
                data = get_data(zip_num, start_date, end_date, typ=wp)
                context_data = {'data': data, 'yr': start_date.year,
                                'mnth': start_date.month, 'day': start_date.day}
                if wp == 'tmp':
                    context_data.update({'wp': 'tmp'})
                elif wp == 'hum':
                    context_data.update({'wp': 'hum'})
                elif wp == 'dew':
                    context_data.update({'wp': 'dew'})
            except Exception as e:
                return render_to_response("plot_graph_faliure.html", {'exception_msg': e},
                        context_instance=RequestContext(request))

            return render_to_response("plot_graph.html", context_data,
                    context_instance=RequestContext(request))
        else:
            return render_to_response("home.html", {'form': form},
                context_instance=RequestContext(request))


def add_station(request):
    """
    """
    form = StationForm()
    if request.method == 'POST':
        # import pdb
        # pdb.set_trace()
        form = StationForm(request.POST)
        if form.is_valid():
            obj = Station(zip_num=form.data['zip_num'], city=form.data['city'],\
                state=form.data['state'])
            obj.save()
            return render_to_response("city_add_success.html",
                context_instance=RequestContext(request))
        else:
            return render_to_response("add_station.html",
                {'form': form},
                context_instance=RequestContext(request))
    return render_to_response("add_station.html", {'form': form},
        context_instance=RequestContext(request))


def plot_graph(request):
    """
    """
    form = CheckWeatherForm()
    if request.method == 'POST':
        form = CheckWeatherForm(request.POST)
        if form.is_valid():
            try:
                # get date from POST request
                city = form.data['city']
                state = form.data['state']
                wp = form.data['wp'] # weather parameter
                station = Station.objects.get(city=city, state=state)
                zip_num = station.zip_num
                sd = form.data['start_date']
                ed = form.data['end_date']
                print self.cleaned_data['start_date']

                # get year , month , day from form date fields
                start_month, start_day, start_year =  sd.split('/')
                end_month, end_day, end_year =  ed.split('/')

                # create date object using yr, mnth, day
                start_date = date(int(start_year), int(start_month), int(start_day))
                end_date = date(int(end_year), int(end_month), int(end_day))

                # get data from wunderground API's
                data = get_data(zip_num, start_date, end_date, typ=wp)
                context_data = {'data': data, 'yr': int(start_year),
                                'mnth': int(start_month), 'day': int(start_day)}
            except Exception as e:
                return render_to_response("plot_graph_faliure.html", {},
                        context_instance=RequestContext(request))

            return render_to_response("plot_graph.html", context_data,
                    context_instance=RequestContext(request))
    return render_to_response("plot_graph_faliure.html", {},
            context_instance=RequestContext(request))

templates/add_city.html
{% extends "base.html" %}

{% block title %} Add City {% endblock %}

{% block content %}
  <p>hiiiiiiiiii</p>
{% endblock %}

templates/add_station.html
{% extends "base.html" %}

{% block title %} Add City {% endblock %}

{% block content %}
  <legend><h1 style="margin-left: 73px;">Add Station Form</h1></legend>
  <form class="contact-form" action="/city/add/" method="post" style="margin-left: 75px;">
    {% csrf_token %}
    <div class="control-group {% if form.zip_num.errors %}error{% endif %}">
      <label>Zip Code</label>
      <div class="controls">
        <input type="text" id="inputZip" placeholder="12312" name="zip_num" value="{{ form.data.zip_num }}">
        {% if form.zip_num.errors %}
          <span class="form-err">{{ form.zip_num.errors }}</span>
        {% endif %}
      </div>
    </div>
    <div class="control-group {% if form.state.errors %}error{% endif %}">
      <label>State</label>
      <div class="controls">
        <input type="text" id="inputState" placeholder="US" name="state" value="{{ form.data.state }}">
        {% if form.state.errors %}
          <span class="form-err">{{ form.state.errors }}</span>
        {% endif %}
      </div>
    </div>
    <div class="control-group {% if form.city.errors %}error{% endif %}">
      <label class="control-label">City</label>
      <div class="controls">
        <input type="text" id="inputCity" placeholder="San Fransisco" name="city" value="{{ form.data.city }}">
        {% if form.city.errors %}
          <span class="form-err">{{ form.city.errors }}</span>
        {% endif %}
        {% if form.non_field_errors %}
          <span class="form-err">{{ form.non_field_errors }}</span>
        {% endif %}
      </div>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} Home {% endblock %}</title>

    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script type="text/javascript">
      $(window).load(function() {
        $(".se-pre-con").fadeOut("slow");;
      });
    </script>
    <link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap.min.css" rel="stylesheet">
    <link href="{{ STATIC_URL }}css/common.css" rel="stylesheet">
    <link href="{{ STATIC_URL }}css/itil.css" rel="stylesheet">
    <script type="text/javascript"></script>
    {% block extra_head %}
    {% endblock %}

  </head>

  <body class="">
    <div class="se-pre-con"></div>

    <div id="wrap">
      <div class="header">
        <div class="wrapper">
          <div class="wrapper-shadow" id="top-nav">
            <div class="brand">
              <a href="/" class="logo">
                <span class="vertical-align logo-image">
                  <i></i>
                  <img class="logo-image" alt="Logo" data-type="logo" src="{{ STATIC_URL }}/logo.jpg">
                </span>
              </a>
              <a href="/" class="logo_text">WUnderground</a>
            </div>
            <div class="header-wrapper">
              <p>Test</p>
            </div>
          </div>
        </div>
        <div class="top_nav_bg">
          <div class="wrapper">
            <div class="wrapper-shadow" id="top-nav1">
              <div class="top_nav">
                <div class="nav_right">
                  <p>Test</p>
                </div>
                <ul class="header-tabs">
                  <li class="active" data-tab-name="dashboard">
                    <span></span>
                    <a href="/" class="icon-gauge">Dashboard</a>
                  </li>
                  <li class="" data-tab-name="tickets"><span></span>
                    <a href="/city/add/" class="icon-ticket" data-keybinding="g t" data-parallel-placeholder="#ticket-leftFilter" data-parallel-url="/helpdesk/tickets/filter_options" data-pjax="#body-container">Add City</a>
                  </li>
                  <li class="" data-tab-name="solutions"><span></span>
                    <a href="#" class="icon-book" data-keybinding="g s" data-pjax="#body-container">More</a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="content" id="body-container">
        <div class="wrapper">
          <div class="wrapper-shadow shadow">
            <!-- <div id="inner"> -->
              <div class="pagearea">
                {% block content %}
                {% endblock %}
              </div>
            <!-- </div> -->
          </div>
        </div>
      </div>

      <div id="footer" class="wrapper">
        <div class="wrapper-shadow">
          <div class="footer-content">
            <a href="#">Submit Feedback</a>
            <span class="muted"> &nbsp;&nbsp;&nbsp;| &nbsp;&nbsp;&nbsp;</span>
            <a href="#">Browse Community</a>
          </div>
        </div>
      </div>
    </div>

    <!--
    <script src="js/jquery-2.1.1.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script src="{{ STATIC_URL }}js/script.js"></script>
    -->
    <script src="http://code.jquery.com/ui/1.10.2/jquery-ui.js"></script>
    <script src="http://code.highcharts.com/highcharts.js"></script>
    <script src="http://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.2/modernizr.js"></script>

    {% block body_foot %}
    {% endblock %}

  </body>
</html>

templates/city_add_success.html
{% extends "base.html" %}

{% block title %} Add City {% endblock %}

{% block content %}
  <p>Station added successfully, Go to <a href="/">home</a> page to check weather.</p>
{% endblock %}

templates/home.html
{% extends "base.html" %}

{% block title %} Home {% endblock %}
{% block extra_head %}
  <script type="text/javascript">
    $(document).ready(function(){
        $("#id_start_date").datepicker();
        $("#id_end_date").datepicker();
    });
  </script>
{% endblock %}

{% block content %}
  <legend><h1 style="margin-left: 73px;">Plot Graph Form</h1></legend></br>
  <form class="contact-form" action="." method="post" style="margin-left: 75px;">
    {% csrf_token %}

      <div class="controls">
        <label>State : </label>
        {{ form.state }}
        <label>City : </label>
        {{ form.city }}
      </div>
      </br>
      <div class="controls">
        <label>Parameters : </label>
        {{ form.wp }}
      </div>
      </br>
      <div class="controls">
        <label>Start Date</label>
        <input type="text" id="id_start_date" placeholder="12/12/2014" name="start_date" value="{{ form.data.start_date }}">
        {% if form.start_date.errors %}
          <span class="form-err">{{ form.start_date.errors }}</span>
        {% endif %}
        <label>End Date</label>
        <input type="text" id="id_end_date" placeholder="12/12/2014" name="end_date" value="{{ form.data.end_date }}">
        {% if form.end_date.errors %}
          <span class="form-err">{{ form.end_date.errors }}</span>
        {% endif %}
        {% if form.non_field_errors %}
          <span class="form-err">{{ form.non_field_errors }}</span>
        {% endif %}
      </div>
    </br></br>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
{% endblock %}

templates/plot_graph.html
{% extends "base.html" %}

{% block title %} Plot Graph {% endblock %}
{% block extra_head %}

  {% if wp == 'tmp' %}
    <script type="text/javascript">
      function plotGraph(yr, mnth, day, data) {
          var chart = {
            zoomType: 'x'
          };
          var title = {
            text: 'Temprature'
          };
          var subtitle = {
            text: 'source wunderground.com'
          };
          var xAxis = {
            type: 'datetime',
            minRange: 24 * 3600000,
            title: {
               text: 'Hours'
            }
          };
          var yAxis = {
            title: {
               text: 'Celcious'
            }
          };
          var legend = {
            enabled: false
          };
          tooltip: {
             valueSuffix: ' *c'
          };
          var plotOptions = {
            // spline: {
               // fillColor: {
               //    linearGradient: { x1: 0, y1: 0, x2: 0, y2: 1},
               //    stops: [
               //       [0, Highcharts.getOptions().colors[0]],
               //       [1, Highcharts.Color(Highcharts.getOptions().colors[0]).setOpacity(0).get('rgba')]
               //    ]
               // },
               marker: {
                  radius: 2
               },
               lineWidth: 1,
               states: {
                  hover: {
                     lineWidth: 1
                  }
               },
               threshold: null
            // }
          };
          var series= [{
            name: 'Temprature',
            pointInterval: 3600000,
            pointStart: Date.UTC(yr, mnth-1, day),
            data: data
            }
          ];

          var json = {};
          json.chart = chart;
          json.title = title;
          json.subtitle = subtitle;
          json.legend = legend;
          json.xAxis = xAxis;
          json.yAxis = yAxis;
          json.series = series;
          json.plotOptions = plotOptions;
          $('#wunderground').highcharts(json);
      }

      $(document).ready(function() {
        var data = {{data}};
        var yr = {{yr}};
        var mnth = {{mnth}};
        var day = {{day}};
        plotGraph(yr, mnth, day, data)
      });
    </script>
  {% elif wp == 'hum' %}
    <script type="text/javascript">
      function plotGraph(yr, mnth, day, data) {
          var chart = {
            zoomType: 'x'
          };
          var title = {
            text: 'Humidity'
          };
          var subtitle = {
            text: 'source wunderground.com'
          };
          var xAxis = {
            type: 'datetime',
            minRange: 24 * 3600000,
            title: {
               text: 'Hours'
            }
          };
          var yAxis = {
            title: {
               text: 'Celcious'
            }
          };
          var legend = {
            enabled: false
          };
          tooltip: {
             valueSuffix: ' *c'
          };
          var plotOptions = {
            // spline: {
               // fillColor: {
               //    linearGradient: { x1: 0, y1: 0, x2: 0, y2: 1},
               //    stops: [
               //       [0, Highcharts.getOptions().colors[0]],
               //       [1, Highcharts.Color(Highcharts.getOptions().colors[0]).setOpacity(0).get('rgba')]
               //    ]
               // },
               marker: {
                  radius: 2
               },
               lineWidth: 1,
               states: {
                  hover: {
                     lineWidth: 1
                  }
               },
               threshold: null
            // }
          };
          var series= [{
            name: 'Humidity',
            pointInterval: 3600000,
            pointStart: Date.UTC(yr, mnth-1, day),
            data: data
            }
          ];

          var json = {};
          json.chart = chart;
          json.title = title;
          json.subtitle = subtitle;
          json.legend = legend;
          json.xAxis = xAxis;
          json.yAxis = yAxis;
          json.series = series;
          json.plotOptions = plotOptions;
          $('#wunderground').highcharts(json);
      }

      $(document).ready(function() {
        var data = {{data}};
        var yr = {{yr}};
        var mnth = {{mnth}};
        var day = {{day}};
        plotGraph(yr, mnth, day, data)
      });
    </script>
  {% elif wp == 'dew' %}
    <script type="text/javascript">
      console.log('dew. pt')
      function plotGraph(yr, mnth, day, data) {
          var chart = {
            zoomType: 'x'
          };
          var title = {
            text: 'Dew Point'
          };
          var subtitle = {
            text: 'source wunderground.com'
          };
          var xAxis = {
            type: 'datetime',
            minRange: 24 * 3600000,
            title: {
               text: 'Hours'
            }
          };
          var yAxis = {
            title: {
               text: 'Percentage'
            }
          };
          var legend = {
            enabled: false
          };
          tooltip: {
             valueSuffix: ' %'
          };
          var plotOptions = {
            // spline: {
               // fillColor: {
               //    linearGradient: { x1: 0, y1: 0, x2: 0, y2: 1},
               //    stops: [
               //       [0, Highcharts.getOptions().colors[0]],
               //       [1, Highcharts.Color(Highcharts.getOptions().colors[0]).setOpacity(0).get('rgba')]
               //    ]
               // },
               marker: {
                  radius: 2
               },
               lineWidth: 1,
               states: {
                  hover: {
                     lineWidth: 1
                  }
               },
               threshold: null
            // }
          };
          var series= [{
            name: 'Dew Point',
            pointInterval: 3600000,
            pointStart: Date.UTC(yr, mnth-1, day),
            data: data
            }
          ];

          var json = {};
          json.chart = chart;
          json.title = title;
          json.subtitle = subtitle;
          json.legend = legend;
          json.xAxis = xAxis;
          json.yAxis = yAxis;
          json.series = series;
          json.plotOptions = plotOptions;
          $('#wunderground').highcharts(json);
      }

      $(document).ready(function() {
        var data = {{data}};
        var yr = {{yr}};
        var mnth = {{mnth}};
        var day = {{day}};
        plotGraph(yr, mnth, day, data)
      });
    </script>
  {% endif %}
{% endblock %}

{% block content %}
  <div id="wunderground" style="width:100%; height:400px;"></div>
{% endblock %}

templates/plot_graph_faliure.html
{% extends "base.html" %}

{% block title %} Plot Graph {% endblock %}

{% block content %}
  <p>Somethng went wrong, Please try again.</p>
  </br>
  <p>Error message: {{ exception_msg }}</p>
{% endblock %}